import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTransition, useState, useMemo } from "react";

const Home: NextPage = () => {
  let [text, setText] = useState("");
  const [isPending, startTransition] = useTransition();
  const [jsxElements, setJSXElements] = useState([]);

  function submit(e) {
    startTransition(() => setText(e.target.value));
  }

  useMemo(() => {
    const map = new Map();
    if (text === "") return;
    text.split(" ").map((word) => {
      let word_occurences = map.get(word);
      if (word_occurences === undefined) map.set(word, 1);
      else map.set(word, word_occurences + 1);
    });
    let result = shuffle_array(generate_jsx(map));
    setJSXElements(result);
  }, [text]);

  function shuffle_array(arr: any[]) {
    arr.forEach((element, index) => {
      let random_index = Math.floor(Math.random() * (arr.length - 1));
      arr[index] = arr[random_index];
      arr[random_index] = element;
    });
    return arr;
  }

  function generate_jsx(words: Map<string, number>) {
    let result: JSX.Element[] = [];
    words.forEach((value, key) => {
      result.push(
        <div
          className="word"
          key={key}
          style={{
            color: `rgb(${value * 4}, ${value * 10}, 80)`,
            fontSize: value * 20,
          }}
        >
          {key + " "}
        </div>
      );
    });
    return result;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input onChange={submit} />
      {isPending ? "pending" : ""}
      <div className="word-map">{jsxElements}</div>
    </div>
  );
};

export default Home;
